import { AgentRegistry } from '../types';

// This mirrors the agent-list.json from the SDK
// In production, this could be fetched from an API endpoint
export const agentRegistry: AgentRegistry = {
  agents: [
    // Infrastructure Agents
    {
      id: 'topic-management-agent',
      name: 'Kafka Topic Management Agent',
      description: 'Manage Kafka topics using natural language. Create, list, delete, and describe topics in your Kafka cluster.',
      category: 'infrastructure',
      endpoint: '/api/agent',
      icon: 'kafka',
      capabilities: ['create-topic', 'list-topics', 'delete-topic', 'describe-topic'],
      status: 'active',
    },
    {
      id: 'database-agent',
      name: 'Database Management Agent',
      description: 'Manage database tables using natural language. Create, list, describe, and drop tables in your H2 database.',
      category: 'infrastructure',
      endpoint: '/api/database-agent',
      icon: 'database',
      capabilities: ['create-table', 'list-tables', 'describe-table', 'drop-table'],
      status: 'active',
    },
    {
      id: 'redis-cache-agent',
      name: 'Redis Cache Agent',
      description: 'Manage Redis cache instances, monitor performance, and optimize cache strategies.',
      category: 'infrastructure',
      endpoint: '/api/redis-agent',
      icon: 'storage',
      capabilities: ['cache-management', 'key-operations', 'performance-monitoring'],
      status: 'coming-soon',
    },
    {
      id: 'mongodb-agent',
      name: 'MongoDB Document Agent',
      description: 'Manage MongoDB collections, indexes, and perform document operations with natural language.',
      category: 'infrastructure',
      endpoint: '/api/mongodb-agent',
      icon: 'database',
      capabilities: ['collection-management', 'document-operations', 'index-optimization'],
      status: 'coming-soon',
    },

    // DevOps Agents
    {
      id: 'kubernetes-agent',
      name: 'Kubernetes Orchestration Agent',
      description: 'Deploy, scale, and manage Kubernetes resources with conversational commands.',
      category: 'devops',
      endpoint: '/api/k8s-agent',
      icon: 'cloud',
      capabilities: ['deploy-pods', 'scale-deployments', 'manage-services'],
      status: 'coming-soon',
    },
    {
      id: 'docker-agent',
      name: 'Docker Container Agent',
      description: 'Build, run, and manage Docker containers and images using natural language commands.',
      category: 'devops',
      endpoint: '/api/docker-agent',
      icon: 'container',
      capabilities: ['container-management', 'image-building', 'docker-compose'],
      status: 'coming-soon',
    },
    {
      id: 'terraform-agent',
      name: 'Infrastructure as Code Agent',
      description: 'Create and manage Terraform configurations, provision cloud resources automatically.',
      category: 'devops',
      endpoint: '/api/terraform-agent',
      icon: 'cloud',
      capabilities: ['terraform-planning', 'resource-provisioning', 'state-management'],
      status: 'coming-soon',
    },

    // Developer Tools Agents
    {
      id: 'code-generator-agent',
      name: 'Code Generation Agent',
      description: 'Generate boilerplate code, refactor existing code, and create unit tests automatically.',
      category: 'developer-tools',
      endpoint: '/api/code-gen-agent',
      icon: 'code',
      capabilities: ['code-generation', 'refactoring', 'test-creation'],
      status: 'coming-soon',
    },
    {
      id: 'api-documentation-agent',
      name: 'API Documentation Agent',
      description: 'Automatically generate and maintain API documentation from your codebase.',
      category: 'developer-tools',
      endpoint: '/api/doc-agent',
      icon: 'book',
      capabilities: ['api-docs', 'swagger-generation', 'changelog-updates'],
      status: 'coming-soon',
    },
    {
      id: 'git-workflow-agent',
      name: 'Git Workflow Agent',
      description: 'Manage Git operations, create branches, handle merge conflicts, and automate Git workflows.',
      category: 'developer-tools',
      endpoint: '/api/git-agent',
      icon: 'git',
      capabilities: ['branch-management', 'merge-operations', 'commit-analysis'],
      status: 'coming-soon',
    },

    // CI/CD & Automation Agents
    {
      id: 'ci-cd-agent',
      name: 'CI/CD Pipeline Agent',
      description: 'Manage CI/CD pipelines, trigger builds, and monitor deployment status across multiple platforms.',
      category: 'cicd-automation',
      endpoint: '/api/cicd-agent',
      icon: 'pipeline',
      capabilities: ['pipeline-management', 'build-triggers', 'deployment-monitoring'],
      status: 'coming-soon',
    },
    {
      id: 'testing-agent',
      name: 'Automated Testing Agent',
      description: 'Create, run, and analyze automated tests including unit, integration, and E2E tests.',
      category: 'cicd-automation',
      endpoint: '/api/testing-agent',
      icon: 'test',
      capabilities: ['test-generation', 'test-execution', 'coverage-analysis'],
      status: 'coming-soon',
    },
    {
      id: 'release-agent',
      name: 'Release Automation Agent',
      description: 'Automate software releases, manage versioning, and generate release notes automatically.',
      category: 'cicd-automation',
      endpoint: '/api/release-agent',
      icon: 'release',
      capabilities: ['version-management', 'release-notes', 'deployment-automation'],
      status: 'coming-soon',
    },

    // Data & Analytics Agents
    {
      id: 'business-analytics-agent',
      name: 'Business Analytics Agent',
      description: 'Generate reports, analyze business metrics, and provide data-driven insights with AI-powered analytics.',
      category: 'data-analytics',
      endpoint: '/api/analytics-agent',
      icon: 'chart',
      capabilities: ['report-generation', 'metric-analysis', 'data-visualization'],
      status: 'coming-soon',
    },
    {
      id: 'etl-pipeline-agent',
      name: 'ETL Pipeline Agent',
      description: 'Create and manage data extraction, transformation, and loading pipelines effortlessly.',
      category: 'data-analytics',
      endpoint: '/api/etl-agent',
      icon: 'pipeline',
      capabilities: ['data-extraction', 'transformation', 'data-loading'],
      status: 'coming-soon',
    },
    {
      id: 'data-quality-agent',
      name: 'Data Quality Agent',
      description: 'Monitor data quality, detect anomalies, and ensure data consistency across systems.',
      category: 'data-analytics',
      endpoint: '/api/data-quality-agent',
      icon: 'quality',
      capabilities: ['quality-checks', 'anomaly-detection', 'data-validation'],
      status: 'coming-soon',
    },

    // Security & Monitoring Agents
    {
      id: 'security-scan-agent',
      name: 'Security Scanning Agent',
      description: 'Scan code for vulnerabilities, detect security issues, and suggest fixes automatically.',
      category: 'security-monitoring',
      endpoint: '/api/security-agent',
      icon: 'shield',
      capabilities: ['vulnerability-scanning', 'security-analysis', 'compliance-checks'],
      status: 'coming-soon',
    },
    {
      id: 'log-analysis-agent',
      name: 'Log Analysis Agent',
      description: 'Analyze application logs, detect errors, and provide intelligent insights from log data.',
      category: 'security-monitoring',
      endpoint: '/api/log-agent',
      icon: 'logs',
      capabilities: ['log-parsing', 'error-detection', 'pattern-analysis'],
      status: 'coming-soon',
    },
    {
      id: 'performance-monitoring-agent',
      name: 'Performance Monitoring Agent',
      description: 'Monitor application performance, track metrics, and get alerts on performance issues.',
      category: 'security-monitoring',
      endpoint: '/api/performance-agent',
      icon: 'performance',
      capabilities: ['metrics-tracking', 'alert-management', 'performance-optimization'],
      status: 'coming-soon',
    },

    // AI & Intelligent Agents
    {
      id: 'customer-support-agent',
      name: 'Customer Support Agent',
      description: 'Handle customer inquiries, ticket management, and provide automated support responses with AI.',
      category: 'ai-intelligent',
      endpoint: '/api/support-agent',
      icon: 'support',
      capabilities: ['ticket-management', 'customer-queries', 'automated-responses'],
      status: 'coming-soon',
    },
    {
      id: 'chatbot-agent',
      name: 'Smart Chatbot Agent',
      description: 'Create and deploy intelligent chatbots for websites, Slack, Teams, and other platforms.',
      category: 'ai-intelligent',
      endpoint: '/api/chatbot-agent',
      icon: 'chat',
      capabilities: ['conversation-management', 'multi-platform', 'intent-recognition'],
      status: 'coming-soon',
    },
    {
      id: 'document-processing-agent',
      name: 'Document Processing Agent',
      description: 'Extract information from documents, PDFs, invoices using AI-powered OCR and NLP.',
      category: 'ai-intelligent',
      endpoint: '/api/doc-processing-agent',
      icon: 'document',
      capabilities: ['ocr-processing', 'data-extraction', 'document-classification'],
      status: 'coming-soon',
    },

    // Integration Hub Agents
    {
      id: 'webhook-manager-agent',
      name: 'Webhook Manager Agent',
      description: 'Create, manage, and monitor webhooks across multiple services and platforms.',
      category: 'integration-hub',
      endpoint: '/api/webhook-agent',
      icon: 'webhook',
      capabilities: ['webhook-creation', 'event-monitoring', 'payload-transformation'],
      status: 'coming-soon',
    },
    {
      id: 'api-connector-agent',
      name: 'API Connector Agent',
      description: 'Connect to third-party APIs, manage authentication, and orchestrate API calls seamlessly.',
      category: 'integration-hub',
      endpoint: '/api/connector-agent',
      icon: 'api',
      capabilities: ['api-integration', 'auth-management', 'request-orchestration'],
      status: 'coming-soon',
    },
    {
      id: 'notification-agent',
      name: 'Notification Hub Agent',
      description: 'Send notifications via email, SMS, Slack, Teams, and other channels from a unified interface.',
      category: 'integration-hub',
      endpoint: '/api/notification-agent',
      icon: 'notification',
      capabilities: ['multi-channel', 'template-management', 'delivery-tracking'],
      status: 'coming-soon',
    },

    // Custom Solutions Agents
    {
      id: 'custom-workflow-agent',
      name: 'Custom Workflow Agent',
      description: 'Build and execute custom business workflows tailored to your organization\'s needs.',
      category: 'custom-solutions',
      endpoint: '/api/custom-workflow-agent',
      icon: 'workflow',
      capabilities: ['workflow-builder', 'task-automation', 'business-logic'],
      status: 'coming-soon',
    },
    {
      id: 'custom-integration-agent',
      name: 'Custom Integration Agent',
      description: 'Create custom integrations for your specific business systems and internal tools.',
      category: 'custom-solutions',
      endpoint: '/api/custom-integration-agent',
      icon: 'puzzle',
      capabilities: ['custom-connectors', 'data-mapping', 'integration-logic'],
      status: 'coming-soon',
    },
  ],
  categories: [
    {
      id: 'infrastructure',
      name: '⚡ Infrastructure',
      description: 'Power your cloud infrastructure - Manage databases, message queues, caching, and storage systems.',
      icon: 'server',
    },
    {
      id: 'devops',
      name: '🔧 DevOps',
      description: 'Orchestrate your operations - Container management, Kubernetes, infrastructure as code, and cloud provisioning.',
      icon: 'settings',
    },
    {
      id: 'developer-tools',
      name: '🚀 Developer Tools',
      description: 'Accelerate your development workflow - Code generation, documentation, Git workflows, and developer productivity.',
      icon: 'code',
    },
    {
      id: 'cicd-automation',
      name: '🔄 CI/CD & Automation',
      description: 'Automate everything, deploy with confidence - Pipeline management, testing automation, and release orchestration.',
      icon: 'pipeline',
    },
    {
      id: 'data-analytics',
      name: '📊 Data & Analytics',
      description: 'Transform data into insights - Business analytics, ETL pipelines, data quality, and visualization.',
      icon: 'chart',
    },
    {
      id: 'security-monitoring',
      name: '🛡️ Security & Monitoring',
      description: 'Secure, monitor, and protect - Security scanning, log analysis, performance monitoring, and alerts.',
      icon: 'shield',
    },
    {
      id: 'ai-intelligent',
      name: '💬 AI & Intelligent Agents',
      description: 'AI-powered automation at your fingertips - Chatbots, customer support, and document processing.',
      icon: 'brain',
    },
    {
      id: 'integration-hub',
      name: '🌐 Integration Hub',
      description: 'Connect all your tools seamlessly - Webhooks, API connectors, and multi-channel notifications.',
      icon: 'link',
    },
    {
      id: 'custom-solutions',
      name: '🧩 Custom Solutions',
      description: 'Your custom-built marketplace agents - Business-specific workflows and tailored integrations.',
      icon: 'puzzle',
    },
  ],
};
