import { AgentRegistry } from '../types';

// This mirrors the agent-list.json from the SDK
// In production, this could be fetched from an API endpoint
export const agentRegistry: AgentRegistry = {
  agents: [
    {
      id: 'topic-management-agent',
      name: 'Kafka Topic Management Agent',
      description: 'Manage Kafka topics using natural language. Create, list, delete, and describe topics in your Kafka cluster.',
      category: 'infrastructure',
      endpoint: '/api/agent',
      icon: 'kafka',
      capabilities: ['create-topic', 'list-topics', 'delete-topic', 'describe-topic'],
      status: 'active',
    },
    {
      id: 'database-agent',
      name: 'Database Management Agent',
      description: 'Manage database schemas, run queries, and optimize database performance using natural language commands.',
      category: 'infrastructure',
      endpoint: '/api/database-agent',
      icon: 'database',
      capabilities: ['schema-management', 'query-execution', 'performance-tuning'],
      status: 'coming-soon',
    },
    {
      id: 'kubernetes-agent',
      name: 'Kubernetes Orchestration Agent',
      description: 'Deploy, scale, and manage Kubernetes resources with conversational commands.',
      category: 'infrastructure',
      endpoint: '/api/k8s-agent',
      icon: 'cloud',
      capabilities: ['deploy-pods', 'scale-deployments', 'manage-services'],
      status: 'coming-soon',
    },
    {
      id: 'redis-cache-agent',
      name: 'Redis Cache Agent',
      description: 'Manage Redis cache instances, monitor performance, and optimize cache strategies.',
      category: 'infrastructure',
      endpoint: '/api/redis-agent',
      icon: 'storage',
      capabilities: ['cache-management', 'key-operations', 'performance-monitoring'],
      status: 'coming-soon',
    },
    {
      id: 'code-generator-agent',
      name: 'Code Generation Agent',
      description: 'Generate boilerplate code, refactor existing code, and create unit tests automatically.',
      category: 'development',
      endpoint: '/api/code-gen-agent',
      icon: 'code',
      capabilities: ['code-generation', 'refactoring', 'test-creation'],
      status: 'coming-soon',
    },
    {
      id: 'api-documentation-agent',
      name: 'API Documentation Agent',
      description: 'Automatically generate and maintain API documentation from your codebase.',
      category: 'development',
      endpoint: '/api/doc-agent',
      icon: 'book',
      capabilities: ['api-docs', 'swagger-generation', 'changelog-updates'],
      status: 'coming-soon',
    },
    {
      id: 'testing-agent',
      name: 'Automated Testing Agent',
      description: 'Create, run, and analyze automated tests including unit, integration, and E2E tests.',
      category: 'development',
      endpoint: '/api/testing-agent',
      icon: 'test',
      capabilities: ['test-generation', 'test-execution', 'coverage-analysis'],
      status: 'coming-soon',
    },
    {
      id: 'ci-cd-agent',
      name: 'CI/CD Pipeline Agent',
      description: 'Manage CI/CD pipelines, trigger builds, and monitor deployment status.',
      category: 'development',
      endpoint: '/api/cicd-agent',
      icon: 'pipeline',
      capabilities: ['pipeline-management', 'build-triggers', 'deployment-monitoring'],
      status: 'coming-soon',
    },
    {
      id: 'business-analytics-agent',
      name: 'Business Analytics Agent',
      description: 'Generate reports, analyze business metrics, and provide data-driven insights.',
      category: 'custom',
      endpoint: '/api/analytics-agent',
      icon: 'chart',
      capabilities: ['report-generation', 'metric-analysis', 'data-visualization'],
      status: 'coming-soon',
    },
    {
      id: 'customer-support-agent',
      name: 'Customer Support Agent',
      description: 'Handle customer inquiries, ticket management, and provide automated support responses.',
      category: 'custom',
      endpoint: '/api/support-agent',
      icon: 'support',
      capabilities: ['ticket-management', 'customer-queries', 'automated-responses'],
      status: 'coming-soon',
    },
  ],
  categories: [
    {
      id: 'infrastructure',
      name: 'Infrastructure',
      description: 'Agents for managing infrastructure components like Kafka, queues, databases, etc.',
      icon: 'server',
    },
    {
      id: 'development',
      name: 'Development',
      description: 'Agents for development tasks like code generation, testing, documentation, etc.',
      icon: 'code',
    },
    {
      id: 'custom',
      name: 'Custom',
      description: 'Custom business-specific agents built by your team.',
      icon: 'puzzle',
    },
  ],
};
